pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=zhaihao
    actions:
      assign:
        users: [zhaihao]
      label:
        add: [dependency-update]
  - name: merge scala-steward's PRs
    conditions:
      - author=zhaihao
      - check-success=TestOnMaster # github action 的check 是 job 的名字
    actions:
      merge:
        method: squash
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}