name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch: #  添加页面手动触发按钮

jobs:
  TestOnMaster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          java-package: 'jre'
          distribution: 'zulu'
          cache: 'sbt'

      - name: Run tests
        run: sbt test
        env:
          GITHUB_TOKEN: ${{ secrets.CI }}
