name: RELEASE

on:
  workflow_dispatch: #  添加页面手动触发按钮

jobs:
  TestOnMaster:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          java-package: 'jre'
          distribution: 'zulu'
          cache: 'sbt'

      - name: Set up Git Config
        run: |
          git config user.name "zhaihao"
          git config user.email "zhaihao@ooon.me"

      - name: Run Release
        run: "sbt 'release with-defaults'"
        env:
          GITHUB_TOKEN: ${{ secrets.CI }}
